/*
   Author  : Md Moniruzzaman Monir
*/



-- TIME DIMENSION CREATION 
  
  
CREATE
  TABLE DIM_TIME
  (
    ID         NUMBER ( 10, 0 ) PRIMARY KEY,
    BEGIN_DATE DATE,
    END_DATE   DATE,
    MONTH      VARCHAR2 ( 5 ),
    MONTH_INT  NUMBER ( 2 ),
    QUARTER    NUMBER ( 1 ),
    YEAR       VARCHAR2 ( 4 ),
    YEAR_INT   NUMBER ( 4 )
  ) ;
    
    
 -- INSERT MONTHLY (MONTH - GRANULARITY)   
    
 -- SYSTEM_DAME is actually SYSDATE in Oracle
    
 INSERT INTO DIM_TIME (ID, BEGIN_DATE, END_DATE, MONTH, MONTH_INT, QUARTER, YEAR, YEAR_INT) 
 WITH TIME_RANGE AS 
 (
   SELECT
      TO_DATE ( '01-Jan-2016', 'DD-MON-YYYY' ) START_DATE, -- 01 JANUARY, 2016
      SYSTEM_DATE END_DATE
   FROM
      DUAL
 )
 SELECT
   TO_NUMBER (TO_CHAR(ADD_MONTHS(TIME_RANGE.START_DATE,(LEVEL-1)),'YYYYQMM')) ID,
   ADD_MONTHS(TIME_RANGE.START_DATE,(LEVEL-1))             MONTH_BEGIN_DATE,
   LAST_DAY( ADD_MONTHS(TIME_RANGE.START_DATE,(LEVEL-1)) ) MONTH_END_DATE,
   TO_CHAR( ADD_MONTHS(TIME_RANGE.START_DATE,(LEVEL-1)),'MON' )           MONTH , 
   TO_NUMBER( TO_CHAR(ADD_MONTHS(TIME_RANGE.START_DATE,(LEVEL-1)),'MM'))  MONTH_INT,
   TO_CHAR(ADD_MONTHS(TIME_RANGE.START_DATE,(LEVEL-1)),'q')               QUARTER,   
   TO_CHAR(ADD_MONTHS(TIME_RANGE.START_DATE,(LEVEL-1)),'YYYY')            YEAR,
   TO_NUMBER(TO_CHAR(ADD_MONTHS(TIME_RANGE.START_DATE,(LEVEL-1)),'YYYY')) YEAR_INT
 FROM 
   TIME_RANGE
 CONNECT BY ( LEVEL - 1 ) <= MONTHS_BETWEEN ( SYSTEM_DATE, TIME_RANGE.START_DATE);
    
    
    
 -- INSERT QUARTERLY (QUARTER - GRANULARITY)
 
 
    
 INSERT INTO DIM_TIME (ID, BEGIN_DATE, END_DATE, MONTH, MONTH_INT, QUARTER, YEAR, YEAR_INT) 
 WITH TIME_RANGE AS
 (
   SELECT
     TO_DATE ( '01-Jan-2016', 'DD-MON-YYYY' ) START_DATE, 
     SYSTEM_DATE END_DATE
   FROM
     DUAL
 )
 SELECT
   TO_NUMBER (TO_CHAR(ADD_MONTHS(TIME_RANGE.START_DATE,(LEVEL-1)*3),'YYYYQ')) ID,
   ADD_MONTHS(TIME_RANGE.START_DATE,(LEVEL-1)*3)   QUARTER_BEGIN_DATE,
   CASE 
     WHEN TO_CHAR (SYSTEM_DATE, 'YYYYQ') = TO_CHAR (LAST_DAY(ADD_MONTHS(TIME_RANGE.START_DATE,(LEVEL-1)*3 + 2) ), 'YYYYQ') 
       THEN LAST_DAY (SYSTEM_DATE)
     ELSE 
       LAST_DAY( ADD_MONTHS ( TIME_RANGE.START_DATE,(LEVEL-1)*3 + 2) )
   END QUARTER_END_DATE,
  'N/A' MONTH , 
   -1   MONTH_INT,
   TO_CHAR(ADD_MONTHS(TIME_RANGE.START_DATE,(LEVEL-1)*3),'q')               QUARTER,   
   TO_CHAR(ADD_MONTHS(TIME_RANGE.START_DATE,(LEVEL-1)*3),'YYYY')            YEAR,
   TO_NUMBER(TO_CHAR(ADD_MONTHS(TIME_RANGE.START_DATE,(LEVEL-1)*3),'YYYY')) YEAR_INT
 FROM 
   TIME_RANGE
 CONNECT BY ( LEVEL - 1 ) <= MONTHS_BETWEEN ( SYSTEM_DATE, TIME_RANGE.START_DATE)/3;
   
   
    
 --INSERT YEARLY (YEAR - GRANULARITY)
 
 
      
 INSERT INTO DIM_TIME (ID, BEGIN_DATE, END_DATE, MONTH, MONTH_INT, QUARTER, YEAR, YEAR_INT) 
 WITH TIME_RANGE AS
 (
   SELECT
     TO_DATE ( '01-Jan-2016', 'DD-MON-YYYY' ) START_DATE, 
     SYSTEM_DATE END_DATE
   FROM
     DUAL
 )
 SELECT
   TO_NUMBER (TO_CHAR(ADD_MONTHS(TIME_RANGE.START_DATE,(LEVEL-1)*12),'YYYY')) ID,
   ADD_MONTHS(TIME_RANGE.START_DATE,(LEVEL-1)*12)   YEAR_BEGIN_DATE,
   CASE 
     WHEN EXTRACT (YEAR FROM SYSTEM_DATE) = EXTRACT ( YEAR FROM LAST_DAY(ADD_MONTHS(TIME_RANGE.START_DATE,(LEVEL-1)*12 + 11) )) 
      THEN LAST_DAY ( SYSTEM_DATE )
     ELSE 
      LAST_DAY( ADD_MONTHS(TIME_RANGE.START_DATE,(LEVEL-1)*12 + 11) )
   END QUARTER_END_DATE,
   'N/A' MONTH , 
   -1    MONTH_INT,
   -1    QUARTER,   
   TO_CHAR(ADD_MONTHS(TIME_RANGE.START_DATE,(LEVEL-1)*12),'YYYY')            YEAR,
   TO_NUMBER(TO_CHAR(ADD_MONTHS(TIME_RANGE.START_DATE,(LEVEL-1)*12),'YYYY')) YEAR_INT   
   
 FROM 
   TIME_RANGE
 CONNECT BY ( LEVEL - 1 ) <= MONTHS_BETWEEN ( SYSTEM_DATE, TIME_RANGE.START_DATE)/12;
    

 COMMIT;
